Добавляет открытие модального окна и валидацию комментария
htmlacademy-javascript/1866821-kekstagram-simple-27 pull request #11
Opened 2022-10-17 14:11 UTC by MihaGoHard

2022-10-17 19:17 UTC, o-bender requested changes

2022-10-17 19:17 UTC, o-bender commented on js/modal.js
> +const closeModalHandler = () => closeModal();
Что бы удовлетворить требования академии это то что нужно. Но в реальной жизни так не делай :)

2022-10-17 19:17 UTC, o-bender commented on js/modal.js
> +const closeModalHandler = () => closeModal();
И так тоже не надо: `const closeModalHandler = closeModal;`

2022-10-17 19:17 UTC, o-bender commented on js/user-form.js
> +const validateSentForm = (userForm) => {
Функция ничего не валидирует, а обещает что проверит отправленную форму. А вместо этого она только устанавливает слушатель.

2022-10-17 19:17 UTC, o-bender commented on js/upload.js
> +const uploadPhoto = (fileInput) => {
Функция не загружает фотку, только устанавливает слушатель.

2022-10-17 19:17 UTC, o-bender commented on js/util.js
> +const photoFormatIsValid = (path) => {
Лучше заменить на validatePhotoFormat или checkPhotoFormat. А то форма с is звучит как "Я есть Грут":)

2022-10-17 19:17 UTC, o-bender commented on js/util.js
> +const isEscapeKey = (evt) => evt.key === 'Escape';
Тут is в общем норм, пусть будет.

2022-10-17 19:17 UTC, o-bender commented on js/util.js
> +const callChangeEvent = (node) => {
Занятный ход. Но на мой взгляд неуместный. Событие это метод асинхронного программирования. Т.е. создавая событие ты планируешь запустить, какую-то целостную операцию выполнение которой:
- либо длительное и ждать её завершения непозволительная роскошь,
- либо второстепенное и ты можешь смириться с его потерей. как udp пакет
- и при работе с асинхронными операциями всегда надо помнить, что операции могут повторяться и последовательность их выполнения предугадать нельзя. Т.е. если вызываешь операции 1, 2, 3, то выполниться они могут как 3,1,2.
В твоём же случае ты разбиваешь одну операцию на несколько. Ставишь событие на обработку и только в следующем цикле обработки event loop-a работаешь со слушателями. При этом ни что не мешает писать так:
```
const uploadOverlay = document.querySelector('.img-upload__overlay');
const closeModalBtn = uploadOverlay.querySelector('#upload-cancel');
const fileInput = document.querySelector('#upload-file');

const toggleUploadOverlayListeners = () => {
    const method = imgUpload.classList.contains('hidden') ? 'removeEventListener' : 'addEventListener';
    closeModalBtn[method]('click', closeModalHandler);
    document[method]('keydown', closeModalKeydownHandler);
};

const openModal = () => {
  fileInput.value = '';
  uploadOverlay.classList.remove('hidden');
  toggleUploadOverlayListeners();
  changeModalGlobalClass();
};
```

2022-10-18 04:35 UTC, MihaGoHard commented on js/modal.js
> +const closeModalHandler = () => closeModal();
Для академии оставлю тогда

2022-10-18 08:27 UTC, merged